In [ ]:
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [10, 11, 12],

In [15]:
import numpy as np
q = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]],[[10, 11, 12],[13, 14, 15],[16, 17, 18]],[[19, 20, 21],[22, 23, 24],[25, 26, 27]]])

In [16]:
q

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [20]:
a10 = np.arange(20)
print(a10)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [21]:
a10.shape

(20,)

In [23]:
q = a10.reshape(4,5) 

In [24]:
q

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [27]:
np_zeros = np.zeros((10,10))

In [28]:
np_zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
np_zeros = np.zeros((2,5))

In [44]:
np_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [55]:
np_full =np.full((3,3), 1)

In [57]:
np_full

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [58]:
np.eye = np.eye(4,8)


In [59]:
np.eye

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.]])

In [68]:
np_linspace = np.linspace(1,20, num=3)

In [69]:
np_linspace

array([ 1. , 10.5, 20. ])

In [70]:
np_rand = np.random.random((2,3))

In [71]:
print(np_rand)

[[0.38351478 0.01289284 0.0534648 ]
 [0.06257441 0.99231535 0.37611861]]


In [73]:
q[[0,2,2], 

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed